### ISSUE TITLE
Easily toggle Tor on accounts with anti-censorship goodies...

### ISSUE THREAD

**Issue by irlcatgirl** [ChatSecure/ChatSecure-iOS#1039]
Sometimes I'm on networks which only allow ports 80 and 443 (and ends up breaking XMPP). I would like to request the following is added to ChatSecure.

- The ability to turn Tor support on and off on a account without removing it first
- The ability to configure Tor bridges (OBFS4?)
- The ability to tell Tor you are behind a firewall which only allows the ports you specify.

Thoughts?

**Comment by chrisballinger** [comment]
There was reasoning behind not allowing you to toggle Tor, because if you created an account with the assumption of anonymity and then turned off Tor, you'd have a big problem.

Right now the Tor support is not in a great state and should be replaced with Tor.framework. There is also a nice user friendly Tor onboarding library that could be useful: https://github.com/guardianproject/poe

**Comment by nsuchy** [comment]
@chrisballinger Tor isn't only an anonymity tool. With accounts it also gives you location privacy. In my case I sometimes use Tor to evade restritive firewalls. It should be a user choice. You can provide a warning screen about the potential consequences of disabling Tor.

**Comment by licaon-kter** [comment]
@nsuchy Your server should provide XEP-0368 maybe.

**Comment by nsuchy** [comment]
Because no one could ever use DPI to determine traffic is XMPP traffic. The solution here is letting other users use Tor as they choose.

**Comment by licaon-kter** [comment]
If you up the game on every answer there will be no solution then. Is your firewall a DPI too? You can't contact port 5222 (with any protocol) or you can't use XMPP (on any port)?

**Comment by nsuchy** [comment]
> If you up the game on every answer there will be no solution then. Is your firewall a DPI too? You can't contact port 5222 (with any protocol) or you can't use XMPP (on any port)?

Port blocking and DPI are in use.

> /LE: Tor relays are at known IPs, your firewall can block those outright, see....escape that then...

@licaon-kter And that's why we have OBFS4 bridges. For the twisted ****s who block Tor traffic and restrict people's right to read.

****

The argument Tor is only useful for anonymity is silly - we should have the freedom to choose whether to use Tor or not and the ability to use bridges.
