### ISSUE TITLE
'tor_cpaproxy.h' file not found

### ISSUE THREAD

**Issue by jgank** [ChatSecure/ChatSecure-iOS#1060]
I followed all of the steps in the Build Instructions. In addition, I changed the bundle identifier and team name. I'm left with 1 error, "'tor_cpaproxy.h' file not found in CPAThread.m. I've tried changing the build scripts as recommended with no luck. I'm using the latest version of Xcode, Version 10.0. I see other people have had the same issue, however, I have not found recent posts about this issue.

I know the issue has to do with the `$ bash ./Submodules/CPAProxy/scripts/build-all.sh` script.

**Comment by ashokt** [comment]
same problem with me also unable to run the full script

**Comment by Snoopy4639** [comment]
I found the same issue !
But i understand command in `/build-all.sh`
in line `export TOR_VERSION="0.3.0.13"` and Command in `/build-tor.sh` will download tor-0.3.0.13 because this command is use version in build-all.sh
But version 0.3.0.13 has been deleted in dist.torproject.org. So command will Error and File Not Found !

If you need to work (Not suggest.) , You must down version tor in `/build-all.sh`
My Project, I use version TOR_VERSION="0.2.9.17" I can build and test in xcode 9.
Everything is ok !!!

I Hope to help you :)

**Comment by ashokt** [comment]
But still i am a rounding with this problem same thing i have changed the version of the TOR_Version in submodules/ cpaproxy/scripts/build-all.sh

but there is still problem 
didnt i need to change the xcode version

**Comment by jgank** [comment]
@Snoopy4639 Thank you so much! It worked!

**Comment by NrmeenTomoum** [comment]
@ashokt  you solved your problem
