### ISSUE TITLE
Chat pane not visible ipad air

### ISSUE THREAD

**Issue by volga629** [ChatSecure/ChatSecure-iOS#1138]
Hello Everyone,
Left pane in chat is not visible on ipad air. Please see attached screenshot.

![D57EF246-2B47-4E17-B761-3539B38BE4E9](https://user-images.githubusercontent.com/3235221/61922506-1c0a2600-af37-11e9-94e2-cf621c79140a.jpeg)

**Comment by chrisballinger** [comment]
I think the issue here is that someone is sending you messages that you can't decrypt on this device and the messages are silently being dropped.

**Comment by volga629** [comment]
Hello Chris,
I checked all OMEMO keys and looks ok. Is should be displayed some message to know that is decryption issue .

**Comment by a11fruitless** [comment]
I suspect this could be fixed with 4.3.9. I saw this too, where it looked like keys were verified, but messgaes still weren't being sent to that device. You should be able to double check by turning off "Best available"/"OMEMO" and switching to "plaintext". If it was the same issue as me, then messages should start working and it is OMEMO related. Then see if the lastest fix solves your problem.

**Comment by volga629** [comment]
Thank you for update, we tested on latest version and everything starts working. On Ipad Air messages arrive as expected. Thank you for quick fix.

**Comment by chrisballinger** [comment]
cheers!
