### ISSUE TITLE
Can't send texts

### ISSUE THREAD

**Issue by rosagp** [ChatSecure/ChatSecure-iOS#322]
I tried to send messages to 2 people that I have sent messages to in the past but they did not go through. They are the only 2 contacts that are showing up in my contacts. However, now when I try and send a message to them I get an error message. 
![img_4237](https://cloud.githubusercontent.com/assets/4604279/6489854/d151f894-c26f-11e4-87f8-82a31ccb20e5.PNG)

**Comment by vingtdeux** [comment]
I'm seeing this issue as well, to people I've never contacted through the app before.

This is happening for existing ChatSecure conversations as well (though without the unlocked lock): 
![img_9273](https://cloud.githubusercontent.com/assets/11226267/6490258/d265dc66-c259-11e4-93ee-248ca57b0427.PNG)

Tapping on the yellow triangle produces the same error message shown by @rosagp.

I think that my last successful message went through shortly after 9am PST, but I didn't notice the problem for existing conversations until this issue was opened and I tested.

**Comment by chrisballinger** [comment]
Is the account connected? 3.1 will have better behavior when the account
has been disconnected and prompt you to reconnect.

**Comment by vingtdeux** [comment]
Thanks/sorry, looks like I had indeed lost my connection. 

BTW, in Compose view you can see who you're sending to and which account it's coming from. In Chats view you don't have that, which can cause confusion if you've got multiple XMPP accounts in the app as I do. I initially thought I'd reproduced this while logged in but realized that I'd entered a conversation from an offline user, not the one I was logged into (the full account names are long/tiny at the top of the screen... I missed it). I'm assuming the 3.1 feedback will clarify that situation, but a from indicator on the Chats screen would catch it sooner (just mentioning here in passing because it sounds like you've got a lot in the works already and maybe it's handled?).
