### ISSUE TITLE
Support for XEP-0357: Push

### ISSUE THREAD

**Issue by iNPUTmice** [ChatSecure/ChatSecure-iOS#367]
Please add support for [XEP-0357: Push](http://xmpp.org/extensions/xep-0357.html). I know you have started working on your own implementation but since there is a XEP for that I believe this would be the better solution. An implementation for ejabberd can be found at [royneary/mod_push](https://github.com/royneary/mod_push)

**Comment by iNPUTmice** [comment]
[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=25760816)](https://www.bountysource.com/issues/25760816-support-for-xep-0357-push?utm_source=25760816&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by chrisballinger** [comment]
Oh yeah, we are working on that as well. Our push solution is complimentary (acts as the app server) component, and I just need to write a pubsub node to translate the xmpp traffic to my own API. 

To work around the lack of server support, we are allowing people to send pushes directly as well, passing the tokens/endpoint information through a specially defined OTR TLV.

**Comment by chrisballinger** [comment]
We actually would like to work with you to integrate our other push solution for a graceful fallback for users on servers that don't support the new XEP. The Android SDK is almost complete and we will be integrating it into ChatSecure soon

**Comment by iNPUTmice** [comment]
Sorry for the late reply. I originally read your comment on my phone and decided to reply later from my desktop computer.

> We actually would like to work with you to integrate our other push solution for a graceful fallback for users on servers that don't support the new XEP

I understand that you might have customers that need your (proprietary) push solution but generally speaking I think it would be advisable to steer users towards upgrading their servers instead of providing them with an easy way out. Using up-to-date servers will not only give you more features (Stream Management, MAM, carbons, PEP (used by OMEMO)) but also increases security (forced PFS on s2s connctions)

I can think of very few reasons for users not to switch to a proper server.

**Comment by chrisballinger** [comment]
Agreed! Our push solution acts as the "app server" component of XEP-0357 that communicates with APNS/GCM directly. It is just a very simple REST API for provisioning devices and sending raw pushes. Our upcoming XMPP PubSub node will simply translate push requests from an XMPP server to our REST API. Totally complimentary efforts.

The design allows users to also send pushes directly to each other via pre-shared tokens (exchanged via OTR TLV), which is what we will be using during the interim period when servers are still adopting 0357. I wouldn't consider it a proprietary design, because it's something that you'll likely need anyway when deploying apps and servers that support 0357. Communicating directly with APNS/GCM from the XMPP server is not ideal because then it means each app developer needs to collaborate with each server operator and distribute credentials / etc.

**Comment by tmolitor-stud-tu** [comment]
I need this, too.
I added $50 bounty for completion.

**Comment by masvil** [comment]
My $5.

**Comment by tmolitor-stud-tu** [comment]
I'd prefer if the pushes were silent VoIP pushes rather than "normal" ones that don't wakeup the app if its closed etc.
