### ISSUE TITLE
Change DB passphrase?

### ISSUE THREAD

**Issue by jgrover** [ChatSecure/ChatSecure-iOS#483]
Looks like the release of version 3.2.1 removed the ability for a user to change their db passphrase.  Where did it get moved to?  Can users no longer do this?

**Comment by chrisballinger** [comment]
It's actually quite difficult to implement properly, and during a YapDatabase upgrade we declined to apply our patches because there were some unresolved race condition issues with them. The database is already encrypted with a strong password, much stronger than something a human could remember.

We felt that it was an underutilized feature compared to the amount of work to support it, so have since discontinued it.

**Comment by stigger** [comment]
OK, so I got a new iPhone. Backed up the old one with iTunes (encrypted backup), then restored on a new phone. Then ChatSecure asked me to enter a passphrase which I never set in the first place.

Why do you even need to encrypt everything again? iOS does a good job doing that on its own, and does it in a secure and efficient way.

**Comment by chrisballinger** [comment]
Apologies, the backup only works when restoring to the same device. In
theory using SQLCipher on the device makes it more difficult to extract
data, for instance, from an unencrypted iTunes backup. We certainly could
do a better job at allowing for an export/backup option because the account
passwords are randomly generated as well.

**Comment by stigger** [comment]
I believe, additional layer of encryption is also a hit on performance/battery consumption. It would be really great if the database encryption was optional: in my case the data on the device and iTunes backups are encrypted, so there is just no need for it.
