### ISSUE TITLE
curl: (56) Received HTTP code 503 from proxy after CONNECT

### ISSUE THREAD

**Issue by loki187** [ChatSecure/ChatSecure-iOS#488]
Hi,

I would like to build and run project, but when I run script for CPAProxy (bash ./Submodules/CPAProxy/scripts/build-all.sh), files are downloading, but after few minutes I end up with this message (see below) and CPAProxy is not installed correctly.

> Making install in sample
> make[3]: Nothing to be done for `install-exec-am'.
> make[3]: Nothing to be done for `install-data-am'.
> Making install in test
> /Applications/Xcode7.3.app/Contents/Developer/usr/bin/make  install-am
> make[4]: Nothing to be done for `install-exec-am'.
> make[4]: Nothing to be done for `install-data-am'.
> ~/Documents/ChatSecure-iOS/Submodules/CPAProxy/scripts/build
> Building tor for i386...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (56) Received HTTP code 503 from proxy after CONNECT
> bash-3.2$

Please, where the problem can be ?

**Comment by loki187** [comment]
Problem was in my proxy settings.

**Comment by swetasharma** [comment]
I'm facing the same issue. Could you please specify the steps you did to resolve it.

**Comment by john612** [comment]
Yes I would like to know the solution as well

**Comment by lfreeitas** [comment]
Hello guys,

In my case the problem was in env and vhost.

Error:
< HTTP/1.1 503 Service Unavailable
< Mime-Version: 1.0
< Date: Wed, 06 Feb 2019 13:44:00 GMT
< Content-Type: text/html;charset=utf-8
< Content-Length: 3564
< X-Squid-Error: ERR_CONNECT_FAIL 111
< Vary: Accept-Language
< Content-Language: en
<
* Received HTTP code 503 from proxy after CONNECT
* Closing connection 0
curl: (56) Received HTTP code 503 from proxy after CONNECT

After adding url to the env of the no_proxy, port 443 failed
We verified that 'https' was not configured on the destination server, after adding the certificate tag and adjusting the vhost the connection could be made.

**Comment by lfreeitas** [comment]
Hello guys,

In my case the problem was in env and vhost.

```
Error:
< HTTP/1.1 503 Service Unavailable
< Mime-Version: 1.0
< Date: Wed, 06 Feb 2019 13:44:00 GMT
< Content-Type: text/html;charset=utf-8
< Content-Length: 3564
< X-Squid-Error: ERR_CONNECT_FAIL 111
< Vary: Accept-Language
< Content-Language: en
<
* Received HTTP code 503 from proxy after CONNECT
* Closing connection 0
curl: (56) Received HTTP code 503 from proxy after CONNECT

```

After adding url to the env of the no_proxy, port 443 failed
We verified that 'https' was not configured on the destination server, after adding the certificate tag and adjusting the vhost the connection could be made.
