### ISSUE TITLE
./Submodules/CPAProxy/scripts/build-all.sh error

### ISSUE THREAD

**Issue by zhaocx871227** [ChatSecure/ChatSecure-iOS#566]
I come from china. when i execute the command,i have this error " checking whether we need extra options to link libevent... configure: error: Found linkable libevent in /Users/zcx/Desktop/ChatSecure-iOS/Submodules/CPAProxy/scripts/built/i386, but it does not seem to run, even with -R. Maybe specify another using --with-libevent-dir}", why?

**Comment by afriedmanGlacier** [comment]
I had the same issue. The problem is the the Tor version in CPAProxy. Here is what I did to fix the problem:
1) Delete the CPAProxy directory from Submodules with the following: rm -rf CPAProxy
2) Re-download the latest CPAProxy from github with: git clone https://github.com/ursachec/CPAProxy.git
3) Re-run the build-all.sh script in CPAProxy/scripts

This fixed the problem for me.

**Comment by zhaocx871227** [comment]
Thank you very much.This also fixed the problem for me.

**Comment by PeterEdens** [comment]
This fixed the problem for me too.
