### ISSUE TITLE
Resend dialog enhancements

### ISSUE THREAD

**Issue by chrisballinger** [ChatSecure/ChatSecure-iOS#599]
- [ ] Additional "View Devices" button for OMEMO no trusted devices error. Brings to Profile screen.
- [ ] Indicate in the dialog somewhere what crypto scheme will be used for the Resend button. "More Options" button to bring to Profile screen?

**Comment by davidchiles** [comment]
Still not 100% on the look or order of the buttons. Could it be something more like "Encryption Settings" or "Profile" instead of "View Devices" so that we could use it with OTR errors as well?
![screen shot 2016-11-08 at 4 13 35 pm](https://cloud.githubusercontent.com/assets/309772/20122700/9a7f6f60-a5ce-11e6-8504-29641f664365.png)

**Comment by chrisballinger** [comment]
Yeah I think "View Profile" could work in both scenarios. Also the OMEMO/OTR text I think should be moved to the alert description so the button is simply "Resend".

```
Unable to Send Message

We could not find any trusted devices for this contact. 
Resending this message will use OMEMO/OTR/Plaintext. (wording?)
View profile to review contact's devices or change encryption settings.

[Resend] (default)
[View Profile]
[OK]
```

**Comment by davidchiles** [comment]
![screen shot 2016-11-09 at 4 16 54 pm](https://cloud.githubusercontent.com/assets/309772/20159817/102eaa18-a698-11e6-8f45-e8d36ab72a77.png)

**Comment by chrisballinger** [comment]
Looks great!

Can you change the title from "Error" to "Unable to Send Message"? Also for some reason I'm feeling that "View Profile" would be better on the top.
