### ISSUE TITLE
Opportunistic OTR Starting Despite Being Turned Off

### ISSUE THREAD

**Issue by a11fruitless** [ChatSecure/ChatSecure-iOS#617]
Hi there. After upgrading to a more recent version of ChatSecure on iOS devices (iPhone and iPad), I have noticed that opportunistic OTR encryption will auto-start when communicating with other devices (e.g. Pidgin; desktop) despite being turned off in the options. Even after it is manually turned off in a chat, once that chat is reopened _after receiving a message_, OTR will re-enable. Is anyone able to confirm this behavior?

**Comment by ronnicek** [comment]
I think it's same issue as #611

**Comment by chrisballinger** [comment]
OTR sessions are automatically re-established when entering a conversation with a contact you've previously used OTR (regardless of opportunistic OTR). We have considered pinning that feature to XMPP full JID / resources instead of bare JIDs, but have been focusing more on releasing OMEMO functionality.

**Comment by chrisballinger** [comment]
Fixed in 3c9f46c
