### ISSUE TITLE
Short stream resumption timeout causes "Replaced by new connection" when used with push notifications enabled

### ISSUE THREAD

**Issue by stigger** [ChatSecure/ChatSecure-iOS#677]
While investigating a problem where ChatSecure fails to reconnect cleanly (https://github.com/ChatSecure/ChatSecure-iOS/issues/361#issuecomment-276714383), I discovered that the current session resumption timeout is too short (5 minutes).

Here is what happens in my case, with ejabberd + mod_push on the server:
1) ChatSecure establishes a stream with timeout 5 minutes
2) After some time ChatSecure closes the socket
3) On the server session switches into "pending" state, mod_push increases the timeout to 24 hours
4) If the next attempt of ChatSecure to reconnect happens after more than 5 minutes, then it considers the stream to be expired and [does not try](https://github.com/robbiehanson/XMPPFramework/blob/master/Extensions/XEP-0198/XMPPStreamManagement.m#L420) to resume it.

This 5 minutes timeout was introduced just recently with 09f8dfde88c9b29acfb84337efa334d4bffaff54. The same commit switched stream management storage from persistent to in-memory, which breaks stream resumption across application relaunches. Unfortunately, from commit it's not clear what were the reasons for both of these changes. @davidchiles, could you please comment on that?

**Comment by chrisballinger** [comment]
@stigger The 5 minute timeout was chosen somewhat arbitrarily. We used to have a timeout of 0 seconds which clearly didn't work very well. What value would you recommend? I based this on the default timeout from mod_smacks. Are you trying to keep the same stream over very long periods of time? I was under the impression it was for short disconnections like going in a tunnel, and not enabled indefinitely.

> The same commit switched stream management storage from persistent to in-memory, which breaks stream resumption across application relaunches.

Due to an outstanding upstream database issue, it appears we can no longer store temporal information like presence in the database without risking looooong blocking sqlite WAL checkpoint pauses, so we need to use an in-memory store. If we persist stream management info to the database it will result in presence info and other temporal states becoming out of sync. So for now we've decided to keep them consistent and both in memory until we can fix the problem in a better way.

**Comment by stigger** [comment]
> The 5 minute timeout was chosen somewhat arbitrarily. We used to have a timeout of 0 seconds which clearly didn't work very well. What value would you recommend? I based this on the default timeout from mod_smacks. Are you trying to keep the same stream over very long periods of time? I was under the impression it was for short disconnections like going in a tunnel, and not enabled indefinitely.

Yes, that's how mod_push in ejabberd works: when the session is in "pending" state the timeout is increased significantly, which effectively keeps the peer always online, because it's always reachable by sending the push.

What problems were you having with timeout of 0? In my opinion, 0 (i.e. not having any timeout) is the best value on the client: just let the server control it.

Of course, it is always possible to reduce the timeout on the server to the same 5 minutes, but in that case [this](http://take.ms/s4zfK) becomes [this](http://take.ms/C3fL8) because iOS wakes up ChatSecure sporadically. I guess, that's one of the reasons why @weiss had chosen increasing the timeout to 24 hours.

**Comment by chrisballinger** [comment]
I think having the peer always appear online is okay, because presence is sort of an outdated concept these days anyway. 

At least on mod_smacks / XMPPFramework, 0 would make the timeout immediate instead of no timeout, so I guess a better default should be chosen. I think more testing needs to be done to make sure a super long timeout doesn't have negative effects for other servers or configurations.

**Comment by stigger** [comment]
XMPPFramework's documentation on `-enableStreamManagementWithResumption:maxTimeout:` implies that the timeout is ignored unless it's a positive value, but the code seems to always perform the local timeout check, even when it's 0. Perhaps, XMPPFramework can be adjusted to make the local check optional.

**Comment by chrisballinger** [comment]
@stigger Good call, tracking here: https://github.com/robbiehanson/XMPPFramework/issues/861

**Comment by chrisballinger** [comment]
Fixed is merged into upcoming 4.0.3 release
