### ISSUE TITLE
friend just installed CS... pain

### ISSUE THREAD

**Issue by gelft** [ChatSecure/ChatSecure-iOS#694]
I'm using the latest gajim on windows.  I have both OMEMO and OTR plugins installed and activated.

he uses:  dukgo.com
I use: movim.eu

Some of his messages I receive cleartext.  Others are the otr announcements 

`has requested an <a href="https://otr.cypherpunks.ca/">Off-the-Record private conversation</a>.  However, you do not have a plugin to support that.`

My interface claims 

`‎OMEMO encryption enabled`

I can see his CS omemo fingerprint.

CS continues to send OTR messages.

1.
How do I direct him to disable OTR?  I don't have an iphone to tinker with myself

2.
why a mix of encryption styles?

3.
Why was he "coerced" into registering at a feature-impaired server like dukgo.com ???!???!?

3b.
Why not one of the top 10  https://gultsch.de/compliance_ranked.html   like jabber.cat or talker.to or even chatme.im ?

**Comment by chrisballinger** [comment]
We will be moving away from using Dukgo as a default server. The server now has a number of issues (not supporting XEP-0357 Push is the most critical), but it also is slow and goes down sometimes. We are collecting a list of semi-trusted public servers here (which are bundled with the app): https://github.com/ChatSecure/xmpp-server-list

Once you send an OMEMO message to them, the client should automatically upgrade to using OMEMO instead of OTR. If that's not happening, there is a bug on our end.

**Comment by Fab2100** [comment]
For me OMEMO works great, but switching back to OTR with conversations on the other side isn't possible. Even if the chatpartner turns OTR in conversations on.

**Comment by chrisballinger** [comment]
The default "OMEMO & OTR" mode doesn't allow you to send text through the OTR channel, it's only sent through the OMEMO channel. The OTR channel is only used to exchange legacy OTRDATA media messages and Knock tokens.  So even if Conversations is sending OTR messages, we will decrypt them and show them in the UI, but all replies will still go through OMEMO. Once we have support for HTTP file transfers we'll be moving to OMEMO-only or OTR-only.

The workaround here is for the ChatSecure user to go to your (i) profile button -> Advanced Encryption Settings -> OTR, which will force OTR.
