### ISSUE TITLE
Bad MAC when receiving malformed PreKeyMessage

### ISSUE THREAD

**Issue by chrisballinger** [ChatSecure/ChatSecure-iOS#743]
I finally was able to see this happening locally, but I really have no idea how to fix it yet. 

```
2017-04-22 20:58:03.413 ChatSecure[94540:3354743] SignalProtocol (2): Bad MAC
2017-04-22 20:58:35.536 ChatSecure[94540:3354743] SignalProtocol (1): Message mac not verified
2017-04-22 20:58:55.878 ChatSecure[94540:3354743] SignalProtocol (1): No valid sessions
```

These are spit out by libsignal-protocol-c when receiving bad prekey messages. Possibly this is related to the bundle corruption issue?

**Comment by chrisballinger** [comment]
I have an idea that this is caused by having multiple local accounts that share buddies w/ the same JID. The SignalAddress and storage stuff is keyed by JID, so sessions could get messed up. We should probably use the `uniqueId` property of the buddy for the address name instead.

**Comment by afriedmanGlacier** [comment]
I am seeing this every time, even if I remove users, delete the app, re-add users with a different JID and start over. In other words, I don't have multiple local accounts.

**Comment by afriedmanGlacier** [comment]
@chrisballinger did you happen to look at the change in https://github.com/WhisperSystems/libsignal-protocol-c/issues/52? That code change occurs in the method that now gives the error.

In looking at what they did, it seems to be an innocuous change, but this wasn't happening in the last version of ChatSecure before the updated libsignal-protocol-c library was used. I tried to build a latest version of ChatSecure with the older libsignal, but had trouble doing so (I think because of SignalProtocol-ObjC) and didn't have a lot of time to mess with it.

**Comment by afriedmanGlacier** [comment]
Agreed.

**Comment by chrisballinger** [comment]
Tracking upstream here: https://github.com/WhisperSystems/libsignal-protocol-c/issues/65
