### ISSUE TITLE
impossible to join a MUC by endering the MUC JID

### ISSUE THREAD

**Issue by mimi89999** [ChatSecure/ChatSecure-iOS#851]
In ChatSecure 4.1.0 it was possible to join a MUC by entering it's JID. In the latest TestFlight version [ChatSecure 4.1.1 (100)]  that isn't possible. Why? @chrisballinger Is that intentional? Maybe @N-Pex accidentally removed it in a code cleanup?

**Comment by weiss** [comment]
> In ChatSecure 4.1.0 it was possible to join a MUC by entering it's JID.

Are you sure?  I've never seen this.  I thought you'd usually either create a room by starting a chat with multiple contacts, or you're invited to an existing room.  I was assuming it's a conscious design decision to not support public rooms in order to keep the UI simple and similar to commercial messengers.  (But I don't know.)

**Comment by chrisballinger** [comment]
I added the functionality in a previous release but literally never tested it, so I'm surprised it ever worked at all. It probably got shuffled around in one of the pull requests. I'm not opposed to adding it back because I think that's a valid (albeit advanced) use case.

**Comment by mimi89999** [comment]
@chrisballinger It  usually worked fine.

**Comment by enko** [comment]
Supporting Booksmarks ([XEP-0048](https://xmpp.org/extensions/xep-0048.html)) would be also very nice!

**Comment by chrisballinger** [comment]
Bookmarks are on the TODO for sure

**Comment by mimi89999** [comment]
Fixed in 4.2.0
